### ISSUE TITLE
how to set the driver class if you are using the latest version of jdbc jar file: com.simba.spark.jdbc42

### ISSUE THREAD

**Issue by stephanieshong** [microsoft/sql-spark-connector#103]
Is there a way to set the java class for the latest version of the JDBC driver? I am using  4.2 version : com.simba.spark.jdbc42

**Comment by shivsood** [comment]
@stephanieshong can u please elaborate further on what exactly do you want to do.

**Comment by shivsood** [comment]
Closing this issue as no response. Please reopen with details if still an issue.
