### ISSUE TITLE
No performance difference between JDBC connector and Spark connector

### ISSUE THREAD

**Issue by sen2arun** [microsoft/sql-spark-connector#104]
We have a requirement to write data from Azure Databricks to Azure SQL and we implemented using JDBC connector, but we see Spark SQL connector will be much more faster than JDBC connector and tried implementing it by following the links. But we could see there is not much difference in the timings between these two.  Below is the code snippet which writes around 8.7 million rows in 20 minutes.  I increase the configuration in Azure SQL and dont see much difference in the timings. Is there any other properties need to set for this?
try: df_merge.write \ .format("com.microsoft.sqlserver.jdbc.spark") \ .mode("overwrite") \ .option("url", url) \ .option("dbtable", table_name) \ .option("user", username) \ .option("password", password) \ .option("bulkCopyBatchSize","400000") \ .option("bulkCopyTableLock","true") \ .option("bulkCopyTimeout","600")

**Comment by User1000** [comment]
I have the same issue, performance is just ~15% better with this connector using these options:
```
.option("reliabilityLevel", "BEST_EFFORT") 
.option("tableLock", "true") \
.option("batchSize","100000") \
```
Driver is used with spark version 3.0.1 and data is written to the azure database. I'm also interested in any parameters that might increase the performance.

**Comment by arvindshmicrosoft** [comment]
There could be many reasons why you are not seeing any major improvement relative to the default JDBC one. The most likely one is the presence of any btree indexes on the destination table. The simplest way is to test with heap tables, and then create your index(es) post facto. Please refer to the following resources for the full details / guidelines:

* [Many useful notebooks from Davide Mauri, showing how to best use bulk insert with partitioning from Spark - in this case, Azure Databricks, and sweeping through the variety of options for table design](https://github.com/Azure-Samples/azure-sql-db-databricks/tree/main/notebooks) (this is perhaps the most practical one for today).
* [For heaps and btrees](https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008/dd425070(v=sql.100)?redirectedfrom=MSDN) (very old, but 100% still valid).
* [For clustered Columnstore](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/columnstore-indexes-data-loading-guidance?view=sql-server-ver15).

**Comment by arvindshmicrosoft** [comment]
@sen2arun @User1000 - I hope my previous comments helped. Do you have any further questions on this? Otherwise I'd like to close this issue.

**Comment by User1000** [comment]
@arvindshmicrosoft thanks for your advices! Disabling indexes really helped. We didn't get 15x better performance but now writing to the db is approximately >2x faster then with using the default connector.

**Comment by arvindshmicrosoft** [comment]
@User1000 - that's good to hear. I'm sure you will find a good solution, based on the schema and overall scenario you are at. Also examine your bulk load batch size etc. Also, please let us know when you are comfortable to close the issue.

**Comment by User1000** [comment]
@arvindshmicrosoft I'm fine with the results I got. But this discussion was opened by @sen2arun and I just shared my experience. Thx again for you help!
