### ISSUE TITLE
Can I ignore errors when writing data into MS SQL?

### ISSUE THREAD

**Issue by jianyu-gong** [microsoft/sql-spark-connector#108]
When I load millions rows into MSSQL, some of rows may have invalided values, for examples null values but the schema in SQL has restriction on null value, and the entire dataframe will be rejected. I am wondering if there is a way to skip rows when experiencing error but keep loading the rest of dataframe into the MS SQL?

**Comment by shivsood** [comment]
Connector write the full dataframe to SQL. Any rows that are not required can be filter out these rows in spark dataframe and then write the filtered dataframe to SQL.
