### ISSUE TITLE
'NO_DUPLICATES reliabilityLevel' option isn't working for v1.0.0-alpha; run into 'com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near &#39;-&#39'

### ISSUE THREAD

**Issue by bellowman** [microsoft/sql-spark-connector#113]
I have a Databricks with a spark 3.11 cluster. I am trying to write data to a Azure SQL database table using sql-spark-connector, v1.0.0-alpha. I run into this issue, 'com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near &#39;-&#39', only when using the option 'NO_DUPLICATES reliabilityLevel'. Other options are fine. My database and server names have '-' in them and I can't change it because they are of the company I work for.

When looking up the error, people said that the server and database name should be in brackets because I have hyphens in their names. I try to as shown below, but doesn't work:

`.option("url", 'jdbc:sqlserver://[test-server].database.windows.net;databaseName=[test-db];')`

**Comment by ChingChuan-Chen** [comment]
This is duplicated with the issue #22

**Comment by luxu1-ms** [comment]
We have this issue fixed in the last commit 92dec61.

**Comment by luxu1-ms** [comment]
We have this issue fixed in the last commit 92dec61

**Comment by matteofaz** [comment]
Hi, am I using version **2.12:1.2.0** of the connector on Databricks on Azure cloud, DBR Runtime 10.4LTS and I am having the same issue only occurring when I use **NO_DUPLICATES** option.

Is there any suggestion, please?

**Comment by moredatapls** [comment]
@matteofaz There's another patch that Microsoft has not released yet which also causes issues with the NO_DUPLICATES mode, see #194 

We at Solytic released binaries that include this patch, you just need to upgrade to our build, see: https://github.com/solytic/sql-spark-connector/releases/tag/v1.2.1

You can give it a try if you want, let me know whether it works
