### ISSUE TITLE
Trying to load tables in parallel

### ISSUE THREAD

**Issue by Smurphy000** [microsoft/sql-spark-connector#119]
I have many tables that need to be loaded into an Azure SQL database from databricks spark job and I want to be able to load them in parallel.
I am using the connector on Spark 3 and running into an issue
```
An error occurred while calling o644.save.
: com.microsoft.sqlserver.jdbc.SQLServerException: There is already an object named '##app-20210526183512-0000_0' in the database.
```

I have defined a function to take source and target parameters

```py
def loadTableToSqlDB(source_db, source_tbl, target_schema, target_tbl, url, user, pw):
  try:
    spark\
      .table(f"{source_db}.{source_tbl}")\
      .write\
      .format("com.microsoft.sqlserver.jdbc.spark")\
      .mode("overwrite")\
      .option("schemaCheckEnabled",False)\
      .option("truncate",True)\
      .option("tableLock",True)\
      .option("reliabilityLevel", "NO_DUPLICATES")\
      .option("url",url)\
      .option("dbtable", f"{target_schema}.{target_tbl}")\
      .option("user", user)\
      .option("password", pw)\
      .save()
```

and then I do a starmap on a threadpool to start loads at the same time rather than sequentially

```py
with ThreadPool(2) as pool:
  pool.starmap(loadTableToSqlDB, args)
```

Loading the tables one at a time works fine, just trying to understand if there is a something I can do to accomplish this or any other suggestions?

It looks like the temporary table name is generated with a timestamp so maybe if I can delay each one by a second, it could do what I want.

**Comment by shivsood** [comment]
Parallel loading will result in tmp table name conflicts.  Today we use appname as table prefix. Suggested enhancement is to take staging table as param and use that. As long as user can keep the prefix unique thru parallel execution this should work. 

@luxu1-ms

**Comment by bellowman** [comment]
Hello, I am also having this issue:

The .option("reliabilityLevel", "NO_DUPLICATES") is causing the problem.
