### ISSUE TITLE
column nullable setting not retained as part of read

### ISSUE THREAD

**Issue by darrenpricedcww** [microsoft/sql-spark-connector#121]
When reading in a column set as not null this is not retained as part of the spark.read.
All columns are showing as nullable = true

Is there a way to change this behaviour to retain the null setting from the source?

**Comment by darrenpricedcww** [comment]
tableName = "dbo.MyTable"

# Read Azure SQL table
df = spark.read \
  .format("com.microsoft.sqlserver.jdbc.spark") \
  .option("url", myJdbcUrl) \
  .option("accessToken", accessToken) \
  .option("dbTable", tableName) \
  .load()

df.printSchema()

**Comment by luxu1-ms** [comment]
@darrenpricedcww Can you try jdbc default connector if it has the same nullable results? replace .format("com.microsoft.sqlserver.jdbc.spark") with .format("jdbc").

**Comment by darrenpricedcww** [comment]
Hi luxu1-ms,

I can confirm I get the same results using just JDBC as advised.
For info the Databricks Synapse Driver (com.databricks.spark.sqldw) is retaining the column null setting as I would expect.

Regards,
Darren

**Comment by shivsood** [comment]
Note : connector delegates read to JDBC driver.

**Comment by darrenpricedcww** [comment]
Hi All,

Do I need to do anytyhing to request this enhancment to the JDBC driver or has that been done?

Thanks,
Darren

**Comment by shivsood** [comment]
@darrenpricedcww default spark JDBC driver enhancements can be requested on the Apache Spark forum.

**Comment by darrenpricedcww** [comment]
Issue logged on Apache Spark website, please vote if anyone else is interested in getting this fixed.
https://issues.apache.org/jira/browse/SPARK-36758

**Comment by luxu1-ms** [comment]
inactive issue.
