### ISSUE TITLE
 java.lang.NoClassDefFoundError: com/azure/core/credential/TokenCredential using JDBC connection columnEncryptionSetting=Enabled  

### ISSUE THREAD

**Issue by aprop** [microsoft/sql-spark-connector#122]
Trying to connect via jdbc to SQL Server with Always encrypt enabled the 

 _java.lang.NoClassDefFoundError: com/azure/core/credential/TokenCredential_ error is returned

The following library has been installed in databricks: 

com.microsoft.azure:spark-mssql-connector_2.12_3.0:1.0.0-alpha
com.azure:azure-core:1.16.0
com.microsoft.azure:msal4j:1.10.0
com.azure:azure-security-keyvault-keys:4.3.0-beta.8

`
user="user"
password="password"
jdbc= "jdbc:sqlserver://server_url,1433;database=mydb;columnEncryptionSetting=Enabled;
KeyStoreAuthentication=KeyVaultClientSecret;KeyStoreSecret=mysecret;KeyStorePrincipalId=myprincipal"

jdbcDF = spark.read \
        .format("com.microsoft.sqlserver.jdbc.spark")  \
        .option("url", jdbc) \
        .option("dbtable", "table") \
        .option("user", user) \
        .option("password", password) \
        .load()

`

Any Idea how to fix it?

**Comment by shivsood** [comment]
Connector passes connection parameters as is. @aprop can u send the stack trace. Not sure why this is class not found and there its coming from.    @DaniBunny @arvindshmicrosoft can u please help on auth settings credentials.

**Comment by aprop** [comment]
Thanks a lot @shivsood, 

going to add additional details:

env Azure Databricks

After changing the default cluster library for the mssql-jdbc driver I was able to perform additional steps. 
Now I'm stuck with faster jackson-core library. The spark cluster uses  the v. 2.7 as default but I need 2.12 for use a method used by azure-core library. Trying to replace the library the cluster does not start.

I will let you know if I will able to fix it, in meantime any help will be very appreciated!

br

**Comment by shivsood** [comment]
Thanks. Closing this as resolved. Please reopen if its a connector issue. Thanks
