### ISSUE TITLE
Unable to connect spark to sql server with sql server installed with docker on linux

### ISSUE THREAD

**Issue by mehmet1092** [microsoft/sql-spark-connector#133]
Hi, 

I would like to connect a spark app to sql server. 
Sql server was installed with docker on linux (https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver15&pivots=cs1-bash)

But when I try to read data from the sql database, I received this error : 
SQLServerException: Login failed for user 'SA'. ClientConnectionId:3bab5203-9d59-44e8-8aa5-eb85650dc739

I was able to connect to the database with this command 
sqlcmd -S <ip_address>,1433 -U SA -P "<YourNewStrong@Passw0rd>"

When I check the internet, it seems that we need to enable SQL Server Authentication with sql server management studio. But how I can do it for sql server inside a container on linux environment ?

Thank you

**Comment by luxu1-ms** [comment]
@mehmet1092 please see below link.
https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/change-server-authentication-mode?view=sql-server-ver15
