### ISSUE TITLE
Getting NoSuchMethodError when trying to append or overwrite data and destination table doesn't exist

### ISSUE THREAD

**Issue by rzeq** [microsoft/sql-spark-connector#135]
I'm using following code to write data into sql server from delta lake:

```
...
table_name = "TEST.TABLE1"
df = spark.sql ("SELECT * FROM table1")
(
df.write
 .format("com.microsoft.sqlserver.jdbc.spark")
  .mode("overwrite")
  .option("url", url)
  .option("dbtable", table_name)
  .option("accessToken", access_token)
  .option("encrypt", "true")
  .option("hostNameInCertificate", "*.database.windows.net")  
  .option("truncate","true")
  .save()
)
```

If table doesn't exists in Azure SQL there is confusing error message:
`java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.schemaString(Lorg/apache/spark/sql/Dataset;Ljava/lang/String;Lscala/Option;)Ljava/lang/String;`

If table exists in Azure SQL everything works fine. 

This also means that mode=overwrite without option truncate=true fails every time.

**Comment by luxu1-ms** [comment]
Hi @rzeq What version of spark are you using? It looks like you have spark version 3.1 or higher. Currently we support spark 2.4 and 3.0. But there is a PR #134 which enables support for 3.1.

**Comment by rzeq** [comment]
I'm using spark 3.1.1 on DBR 8.2 cluster.

**Comment by luxu1-ms** [comment]
Currently the released spark mssql connector jars are only for spark 2.4 / 3.0. please try corresponding spark versions or build spark 3.1 jar from #134. We will release spark 3.1 jar soon.
