### ISSUE TITLE
write fails with key not found 

### ISSUE THREAD

**Issue by johnayoub** [microsoft/sql-spark-connector#137]
I have a sql table with 121 columns in it and a dataframe with only a subset of those around 20. Whenever I try to save with append it seems that dataframe should have the same exact columns which doesn't make any sense. I have the schema check disabled. Does the connector support writing only a subset of the columns?

I'm testing with Databricks 8.4 runtime and the latest connector version.

**Comment by johnayoub** [comment]
@luxu1-ms can you please chime in on this issue?

**Comment by luxu1-ms** [comment]
@johnayoub The SQL Server bulk copy validates the source df and target sql table column mappings. It will raise error if the column counts are not equal.  Connector uses bulk copy methods, thus there are not much can be done in connector side.

**Comment by luxu1-ms** [comment]
Close inactive issue.
