### ISSUE TITLE
Fails with method not found error when used with Spark 3.1.2

### ISSUE THREAD

**Issue by zzhu-bh** [microsoft/sql-spark-connector#140]
Fails with method not found error when used with Spark 3.1.2.  Happy to provide more details on this, but I'm guessing Spark 3.1.x is not yet supported and that's the issue.

**Comment by luxu1-ms** [comment]
the spark mssql connector supporting spark 3.1x (v1.2.0) is now available in Maven Central. https://mvnrepository.com/artifact/com.microsoft.azure/spark-mssql-connector
