### ISSUE TITLE
Link to CHANGELIST giving 404 error

### ISSUE THREAD

**Issue by darrenpricedcww** [microsoft/sql-spark-connector#143]
Please fix link the CHANGELIST, looking for changes between 1.0.0-alpha & 1.2.0

https://github.com/microsoft/sql-spark-connector/blob/master/docs/CHANGELIST.md

**Comment by luxu1-ms** [comment]
Please see the changelist here https://github.com/microsoft/sql-spark-connector/blob/master/CHANGELIST.md
1.1.0-alpha is for spark 3.0, 1.2.0 is for spark 3.1. 1.2.0 version also added brackets for staging table name for NO_DUPLICATES mode.
