### ISSUE TITLE
Compiliation failed with sbt 

### ISSUE THREAD

**Issue by jlachniet-mwhc** [microsoft/sql-spark-connector#156]
Hi, Not sure this is the right place to ask this, but I am receiving a "compiliation failed" error every time I try to build a jar with this repo using sbt. These errors are detailed as "object is not a member of package org" for many packages before it fails completely. I have not modified any of the dependencies in the package. I have tried changing the version of sbt and java and am still receiving the same errors. 

spark = 3.2.0
java = 1.8.0_301
sbt = 1.5.5
hadoop = 2.7.0

**Comment by luxu1-ms** [comment]
@jlachniet-mwhc After we satrted to support Spark 3.0 (PR #76), the sbt build is not supported. Please try maven build, mvn package. Or please see the connector jars in Maven central repository.
