### ISSUE TITLE
Column 'XX_ID' has a data type that cannot participate in a columnstore index

### ISSUE THREAD

**Issue by wikri87** [microsoft/sql-spark-connector#161]
I'm having trouble writing my dataframe to an sql server using azure databricks notebook.

`table("tableviewname").write.mode("overwrite").format("com.microsoft.sqlserver.jdbc.spark").option("url", url).option("dbtable", "dbo.newtable").option("user", username).option("password", password).option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver").save()`

The error message is: com.microsoft.sqlserver.jdbc.SQLServerException: The statement failed. Column &#39;XX_ID&#39; has a data type that cannot participate in a columnstore index.

Can you help me with this issue?

Thanks

**Comment by luxu1-ms** [comment]
Please refer below link for columnstore index datatypes. I guess your column datatype is not in that list. https://docs.microsoft.com/en-us/sql/t-sql/statements/create-columnstore-index-transact-sql?view=sql-server-2017#LimitRest

**Comment by wikri87** [comment]
I can write the table using the native jdbc connector without any problem. The column XX_ID is an NVARCHAR and I don't see how I can change the datatype on a spark dataframe. Any idea how to fix this ?

**Comment by luxu1-ms** [comment]
I think this issue is related with mssql jdbc. Could you pls share us the repro?

**Comment by luxu1-ms** [comment]
close inactive incident.
