### ISSUE TITLE
Spark 3.2 Support

### ISSUE THREAD

**Issue by furlong46** [microsoft/sql-spark-connector#164]
It would be awesome if there was Spark 3.2 support.

**Comment by sagmansercan** [comment]
Is there any document/checklist of required changes for spark 3.2 support?

**Comment by moredatapls** [comment]
While there is no official support for Spark 3.2.0, I used version 1.2.0 of the connector with it anyways and it has been working fine for me for a few months. It only broke after upgrading to Spark 3.3, see also my issue #191

**Comment by balintbako** [comment]
Is there an ETA for supporting Spark 3.2?

**Comment by moredatapls** [comment]
@balintbako @sagmansercan @furlong46 since Microsoft is not really responding anymore we created a fork and released a version with Spark 3.2 support. Follow the instructions here to get the build: https://github.com/solytic/sql-spark-connector/releases/tag/v1.3.0

**Comment by luxu1-ms** [comment]
Close this issue as the current connector v 1.2.0 supports spark 3.2
