### ISSUE TITLE
preactions/postactions feature in options

### ISSUE THREAD

**Issue by saiprasadcrown** [microsoft/sql-spark-connector#168]
Require preactions and postactions feature during the write operation to the SQL db, this will enable the user to run custom SQL on the table and establish a durable and robust pipeline,

**Comment by luxu1-ms** [comment]
@saiprasadcrown Could you share more details about preaction / postactions features?

**Comment by saiprasadcrown** [comment]
let's say I'm using the write operation to the SQL server, I would need an option in the df.write to run custom SQL before the data frame write operation, this will enable me to perform delete/insert or truncate/insert the data on the table, this feature is similar to the redshift library 

search for option preaction/postaction in below link 
https://github.com/databricks/spark-redshift


<html>
<body>


preactions | No | No default | This can be a ; separated list of SQL commands to be executed before loading COPY command. It may be useful to have some DELETE commands or similar run here before loading new data. If the command contains %s, the table name will be formatted in before execution (in case you're using a staging table).Be warned that if this commands fail, it is treated as an error and you'll get an exception. If using a staging table, the changes will be reverted and the backup table restored if pre actions fail.
-- | -- | -- | --



</body>
</html>

**Comment by luxu1-ms** [comment]
@saiprasadcrown You may try spark df operations before write with spark mssql connector.

**Comment by bryan-goodrich** [comment]
@luxu1-ms Using dataframe operations does not satisfy this feature. Other JDBC drivers (AWS, Redshift) allow for pre/post actions as prepared statements, separated as SQL expressions are by semi-colons.

The benefit of these additional actions is that you can setup or drop temp tables on the DB side in your actions. You can land a dataframe write into a staging table and call a SQL insert statement to move it (or partition swap or run a stored procedure). Thus, the flexibility is that other database-side engineering actions can be taken from within the same JDBC call. 

Workaround now is to simply do something like this before or after the JDBC write

```
postactions = "put the actions here"
manager = spark._sc._gateway.jvm.java.sql.DriverManager
conn = manager.getConnection(url, user, password)
conn.prepareCall(postactions).execute()
conn.close()
```

**Comment by luxu1-ms** [comment]
The connector is using SQL Server JDBC. If JDBC does not support for pre/post actions, the connector cannot add these actions.

**Comment by moredatapls** [comment]
@luxu1-ms: I believe it should be possible to use the SQL Server JDBC to implement pre- and postactions. One could add two more fields "preactions" and "postactions" to the `SQLServerBulkJdbcOptions` class - similar to "query" or "dbTable". If those actions are present, the queries could be executed using a JDBC connection before or after reading/writing the data to/from SQL server, inside the connector. I think this issue should be reopened and I think it is a valid feature request
