### ISSUE TITLE
Very slow to write to Azure SQL

### ISSUE THREAD

**Issue by timgautier** [microsoft/sql-spark-connector#170]
Due to a recent company merger we run Spark on AWS and need to write to Azure SQL. We regularly write to MySQL and Postgresql and it's very fast, but we're finding that writing to SQL Server with the jdbc driver is unusably slow. I thought I'd try out this library due to the claimed speed, but I'm just not seeing any noticeable improvement. 

My dataframe is about 28M rows, and I killed this after an hour when it had only written about 11M rows.

`    val properties = new java.util.Properties()`
`    properties.put("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")`
`    df.write.`
`      mode(SaveMode.Overwrite).`
`      option("truncate", true).`
`      option("schemaCheckEnabled", false).`
`      option("batchSize","1048576").`
`      option("tableLock", "false").`
`      jdbc(dbConnectionMap("url"), "spark_test", properties)`

I've tried with numerous settings and have never seen an acceptable result. It's possible this connector is faster than the default and I'm just not seeing the difference because I give up and kill them both, but it doesn't really matter if it's still too slow to use.

For reference, the solution we came up with is to repartition the dataframe to a single partition, write it to s3 as a single csv file, call a lambda function to transfer the csv file from s3 to azure blog storage, then do a bulk insert on that csv file. As convoluted as this solution is, it's dramatically faster than just writing to sql server directly.

`   Writing csv: Wed Jan 12 17:07:57 UTC 2022`
`    Done writing csv: Wed Jan 12 17:09:06 UTC 2022`
`    Calling lambda and waiting for transfer to azure: Wed Jan 12 17:09:08 UTC 2022`
`    File exists on azure: Wed Jan 12 17:10:32 UTC 2022`
`    Executing bulk insert Wed Jan 12 17:11:00 UTC 2022`
`    Complete bulk insert after: 4:17`

That's about 8 minutes total for 28M rows versus an hour for less than half that.

Is there a solution to this? I'm not seeing anywhere near the speeds you're claiming in your docs. This doesn't seem to be a database server induced limit since I can bulk insert the same data in 4 minutes from a csv file.

**Comment by arvindshmicrosoft** [comment]
I suspect / wonder if the over-the-wire latency of the SQL connection going from AWS to Azure, is the main bottleneck here, which may explain why you don't see improvements vis-a-vis regular row-by-row JDBC inserts. I presume the AWS Spark cluster is roughly in the same geo as the Azure DC. If not, that's already an anti-pattern. Even if they are roughly in the same geo, it would still be an "across-the-Internet" hop, not quite optimal. We don't usually see these scenarios across cloud providers, as the SQL TDS protocol over the WAN would still be chattier than a straight pull from some cloud storage. An alternative to possibly try is to run the Spark compute on Azure, mount or access your S3 buckets from that cluster in Azure, and let Spark connect to Azure SQL DB locally.

I am curious about the mitigation case:
> then do a bulk insert on that csv file. As convoluted as this solution is, it's dramatically faster than just writing to sql server directly.

**Question 1:** In the above case, did you try running the Spark connector running inside some Spark compute in Azure, with that single CSV file? Did you try with multiple CSV files concurrently, within Azure? Do you see any differences between single CSV and multiple CSV?

The reason for asking about single CSV vs. multiple concurrent CSVs being used, is that if your target table has any indexes on it - be it clustered, or non-clustered, having multiple writers bulk copying data at the same time into that single table with indexes, is going to be slow due to the overhead of the index maintenance, and locking mechanisms associated with the btree(s). Our recommended practices are to either use heaps (row store tables without any indexes), or clustered columnstores. See the [azure-sql-db-databricks](https://github.com/Azure-Samples/azure-sql-db-databricks) repo for more detailed examples if interested.

**Question 2:** Is it possible to clarify what kind of table is the target table (heap / btree / clustered columnstore)?

Finally, when you say:
> We regularly write to MySQL and Postgresql and it's very fast, but we're finding that writing to SQL Server with the jdbc driver is unusably slow.

**Question 3:** Are the MySQL / PG instances also in Azure, and you write to them from Spark in AWS? If that is the case, and your SQL loads are slower, it is highly likely due to the presence of indexes on the target table. I can't be sure without more specifics, but this is typically what we see.

**Comment by timgautier** [comment]
No, we haven't tried running Spark on Azure. It's possible we may try that in the future, but as of yet we haven't seen a way to get comparable pricing on Azure since we run our Spark clusters on spot instances. We're in an odd situation due to the merger of two companies, one of which is 100% on Azure the other is 100% on AWS.
We also haven't tried multiple concurrent csv files. Right now I'm just writing to a test table in Azure that has no indexes at all. The table is being created by the Spark write. In practice, we tend to write to temp tables without indexes, then add what constraints we need, drop the original and rename the new one.
The MySQL/ PG DBs we write to are running in AWS, so you're correct that latency may be the bottleneck when writing to Azure SQL.

**Comment by arvindshmicrosoft** [comment]
> since we run our Spark clusters on spot instances.

FYI Azure Databricks [does support](https://docs.microsoft.com/en-us/azure/databricks/clusters/configure#--spot-instances) spot instances.

If you do have a chance, please consider re-doing your test using the Spark connector with Azure based Spark compute in the same Azure region as the target Azure SQL DB. I suspect it will be the solution to this. It may also be worthwhile using Azure Databricks to read directly from S3 (this is not officially documented but I believe it works) and write to Azure SQL DB. Again, the Spark and SQL should be co-located in the same Azure region to eliminate any WAN / Internet latencies.

**Comment by timgautier** [comment]
Yeah, we did see we could run on spot instances if we pay for Databricks, but we don't come out ahead in server cost by doing that.
I will look into running a test on azure spark soon since our data transfer costs may end up making up the difference.

**Comment by B4PJS** [comment]
Ok, a few points to note on your configuration which should help speed things up:
1. Your batch size is set to the batch size for a table with a clustered columnstore index on it. As you are writing to a heap you should set your batch size to 10000
2. Set your table lock to true
3. Repartition your dataframe to the same number as cores available on your sql db

**Comment by timgautier** [comment]
Thanks for the tip, but I've tried all those things plus many more and not seen improvement. We'll be getting spark running in Azure soon I think and we'll see if that helps.

**Comment by timgautier** [comment]
OK, we have Spark running in Azure now and I was able to test this out. I can't say I'm seeing any measurable difference. With tablock=true and reliability level of best effort, it's still moving at a pace to take over 2 hours to insert this same data.

Is there something I have to do to get the connector to bulk insert? As far as I can tell it only does row by row inserts, which explains why I see no improvement over a generic jdbc connector.

**Comment by arvindshmicrosoft** [comment]
@timgautier - is it possible for you to now open a support ticket through the Portal and thereby get some direct help?

Where is the source data frame getting its data from? Is it from S3? If the source is still S3, I recommend perhaps doing an intermediate `df.cache` to force a complete read from S3 and cache in-memory, before writing to SQL. This will help isolate if the source or the sink (SQL DB) is the problem. If the read from S3 itself is time consuming, maybe that is the problem.

However, if the sink (SQL DB) is determined to be the bottleneck:
0. Check if SQL DB is resource constrained in any way (CPU, data or log I/O)
2. Check Azure SQL DB wait stats (either by querying sys.dm_os_wait_stats or by looking at Query Store wait stats data) for the time period when Spark is loading the data.
3. Using Query Store information, you can precisely tell whether (or not) the connector is indeed using the Bulk API correctly. If you see INSERT BULK... statements at the top of the resource intensive queries for the time period when your load is running we can be sure it is using the bulk insert path.

**Comment by timgautier** [comment]
For this test I'm literally just reading from a sql table and writing it back out into a test table. I do cache the table and force an action (df.count) to ensure it's entirely loaded into spark before starting the write.

It's not a database constraint issue as I'm able to write this exact same data out to a csv in blob storage and then load it with a bulk insert statement in sql server in under 10 minutes.

Watching the queries that are being performed, they are definitely not bulk insert queries and I'm sure that's the cause of the slowness. I know the old discontinued version of this connector had a specific function to do bulk inserts, but as I understand it, this new version does not. Is there something I'm supposed to do to make it bulk insert data? I'm not seeing anything in the documentation that describes this. 

In fact, this: 

> The Apache Spark Connector for SQL Server and Azure SQL is based on the Spark DataSourceV1 API and SQL Server Bulk API and uses the same interface as the built-in JDBC Spark-SQL connector. This allows you to easily integrate the connector and migrate your existing Spark jobs by simply updating the format parameter with com.microsoft.sqlserver.jdbc.spark.

seems to indicate I don't need to do anything special to make the connector use bulk inserts, but that's not the behavior I'm seeing.

**Comment by arvindshmicrosoft** [comment]
Do you have the `.format("com.microsoft.sqlserver.jdbc.spark")` included in your df.write call?

**Comment by timgautier** [comment]
`      df.write.format("com.microsoft.sqlserver.jdbc.spark").mode(SaveMode.Overwrite).
        option("dbtable", "spark_test").
        option("batchsize", 10000).
        option("tableLock", "true").
        option("reliabilityLevel", "BEST_EFFORT").
        jdbc(dbConnectionMap("url"), "spark_test", properties)
`
This is the last test call I ran.

**Comment by arvindshmicrosoft** [comment]
Hmm... why do you have the .jdbc at the end? I believe that will fall back to row-by-row. Try following the sample as-is:

```
 df.write \
    .format("com.microsoft.sqlserver.jdbc.spark") \
    .mode("overwrite") \
    .option("url", url) \
    .option("dbtable", table_name) \
    .option("user", username) \
    .option("password", password) \
    .save()
```

**Comment by timgautier** [comment]
```
22/03/24 21:04:40 DEBUG com.microsoft.sqlserver.jdbc.spark.SQLServerBulkJdbcOptions: Keytab path found, assuming manual upload
22/03/24 21:04:40 DEBUG com.microsoft.sqlserver.jdbc.spark.SQLServerBulkJdbcOptions: Keytab path found, assuming manual upload
java.lang.NoSuchMethodException: org.apache.spark.sql.execution.datasources.jdbc.DriverWrapper.<init>()
  at java.base/java.lang.Class.getConstructor0(Unknown Source)
  at java.base/java.lang.Class.getConstructor(Unknown Source)
  at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:54)
  at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.$anonfun$createConnectionFactory$1(JdbcUtils.scala:62)
  at com.microsoft.sqlserver.jdbc.spark.DefaultSource.createRelation(DefaultSource.scala:56)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:75)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:73)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:84)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.$anonfun$applyOrElse$1(QueryExecution.scala:110)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
  at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
  at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:110)
  at org.apache.spark.sql.execution.QueryExecution$$anonfun$eagerlyExecuteCommands$1.applyOrElse(QueryExecution.scala:106)
  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:481)
  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:82)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:481)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:30)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:267)
  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:263)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
  at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:30)
  at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:457)
  at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:106)
  at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:93)
  at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:91)
  at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:128)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:848)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:382)
  at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:355)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:247)
  at $anonfun$res5$1(<console>:57)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)

```

I get this error when I call save. Seems it's trying to use the bulk functionality.

**Comment by timgautier** [comment]
df.write
        .format("com.microsoft.sqlserver.jdbc.spark")
        .mode("overwrite")
        .option("url", url)
        .option("dbtable", "spark_test")
        .option("user", dbUser)
        .option("password", dbPassword)
        .option("database", dbName)
        .option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")
        .save()

This is working. Issuing `BULK INSERT` statements now.

I see what happened. When calling `.jdbc`, you supply a `java.util.Properties` object, which typically contains the driver class name. If you call `.save` without giving the driver class name in the options, it errors. This is why I used `.jdbc` instead of `.save`. It's what I use for other databases and bulk insert into them fine, but doesn't work the same in SQL Server.

On the front page is this example:
```
df.write \
    .format("com.microsoft.sqlserver.jdbc.spark") \
    .mode("append") \
    .option("url", url) \
    .option("dbtable", table_name) \
    .option("user", username) \
    .option("password", password) \
    .save()
```
Which is pySpark, not Scala Spark, but looks almost identical. It seemed trivial to convert it to Scala, but that extra option required for Scala makes a big difference.

Thanks for the help, I'm going to finish up my testing and then I'll close this. I assume it'll be fast now.

**Comment by luxu1-ms** [comment]
@timgautier 
Could you try to increase the batch size? The ideal batch size should be larger than each partition size in your dataframe.
