### ISSUE TITLE
Overwrite option question

### ISSUE THREAD

**Issue by baatch** [microsoft/sql-spark-connector#171]
Hi,

I'm wondering about the overwrite option. Is it dropping/truncating the table and then inserting in a single transaction? Or will there be a time windows when the table does not exist or is truncated?

**Comment by luxu1-ms** [comment]
@baatch If the table exists, overwrite option with isTruncate=true will truncate the table, then insert to the table. Overwrite option with isTruncate not true will drop the table, then create the table, then insert to it.

**Comment by luxu1-ms** [comment]
close inactive incident
