### ISSUE TITLE
NoSuchMethodError exception when trying to append data

### ISSUE THREAD

**Issue by suryakirantnv** [microsoft/sql-spark-connector#173]
Hi, 

I am getting this exception java.lang.NoSuchMethodError: com.microsoft.sqlserver.jdbc.SQLServerBulkCopy.writeToServer(Lcom/microsoft/sqlserver/jdbc/ISQLServerBulkData;)V while trying to save data in append mode. I am using below versions
scala>2.1
spark>3.1.2
mssql-jdbc>8.4.1.jre8 (tried 9.2.1.jre8 version as well)
spark-mssql-connector_2.12>1.2.0

I am using a Java project and the maven dependencies are like below. 
```
    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>spark-mssql-connector_2.12</artifactId>
      <version>1.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>8.4.1.jre8</version>
    </dependency>
```

Code as below 
```
dataset.write()
              .format("com.microsoft.sqlserver.jdbc.spark")
              .option("url", getDbServerUrl())
              .option("driver", config.getDatabaseConfiguration().getDriverClass())
              .option("dbtable", tableName)
              .option("user", dbUserName)
              .option("password", getDbPassword())
              .option("batchsize", 10000)
              .option("schemaCheckEnabled", "false")
              .mode(SaveMode.Append)
              .save();
```
Can someone please help.

**Comment by luxu1-ms** [comment]
@suryakirantnv We are using Scala version 2.12. Could you check your jdbc version? I guess the spark mssql connector you use is compatible with jdbc 8.4.1, but the jdbc in your environment is jdbc-7.*

**Comment by luxu1-ms** [comment]
close inactive incident
