### ISSUE TITLE
Signer Information Security Exception 

### ISSUE THREAD

**Issue by Rap70r** [microsoft/sql-spark-connector#175]
Hello,

I'm using AWS Glue to run a simple Spark job. I have downloaded the jar file from below location:

Spark Connector: https://search.maven.org/artifact/com.microsoft.azure/spark-mssql-connector_2.12/1.2.0/jar

and got sql server jdbc connector from below location:

JDBC Driver For SQL Server: https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/8.4.1.jre8

I included both jars into the class path. When I run the job I get below exception:

`Exception in User Class: java.lang.SecurityException : class "com.microsoft.sqlserver.jdbc.ISQLServerBulkData"'s signer information does not match signer information of other classes in the same package`

Can you please help me resolve this?

Thank you

**Comment by luxu1-ms** [comment]
Looks like issue of multiple JDBC jars in your class path / environment. Please reopen with logs if still an issue.

**Comment by girimedi** [comment]
I m had the same issue. I tired to resolve it by setting --user-jars-first to true on the glue job parameters. But then I got 
different error and i am opening a new issue for it
