### ISSUE TITLE
 java.sql.SQLException: No suitable driver

### ISSUE THREAD

**Issue by krishnenduGupta** [microsoft/sql-spark-connector#177]
Code which I have used

![image](https://user-images.githubusercontent.com/15143390/158617502-7cd9a033-b072-496f-b477-3433986552d2.png)

Packages installed on cluster.(All though I am not using AAD authentication) I created this cluster newly. 

Databricks Runtime :9.1 LTS (includes Apache Spark 3.1.2, Scala 2.12)

!
![image](https://user-images.githubusercontent.com/15143390/158615090-59f7a38c-40c3-49c7-99bc-b3b06b5a8d0f.png)

Added a init file at cluster level

dbutils.fs.put("/databricks/init/scripts/sqlremovejar.sh",
"""#!/bin/bash
rm /databricks/jars/*mssql*
""")

![image](https://user-images.githubusercontent.com/15143390/158616833-2962db79-f045-4b1b-90d9-ec3b02f0b9da.png)

**Comment by sumitppawar** [comment]
@krishnenduGupta  
Adding below option working for me 

```python
.option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver") 
```

**Comment by krishnenduGupta** [comment]
@sumitppawar  
Thanks the solution worked, but I had to add  upload a jar file for  jdbc connector. 

Just one suggestion If these steps can be  a part document then it would been very easy.  Many Thanks

**Comment by vlasvlasvlas** [comment]
> low

hi, this didnt work for me, do you need to change the imports or what libraries do you need installed?

**Comment by vlasvlasvlas** [comment]
> orked, but I had to add upload a

what change you need to add? thanks

**Comment by syedhassaanahmed** [comment]
As @krishnenduGupta suggested, the `.option("driver", "com.microsoft.sqlserver.jdbc.SQLServerDriver")` part should be documented.
