### ISSUE TITLE
No Maven-release

### ISSUE THREAD

**Issue by bbs-csel** [microsoft/sql-spark-connector#18]
The old connector (https://github.com/Azure/azure-sqldb-spark) was released on Maven for easy consumption, where as this needs to be build from scratch ourselves, which is one more piece to maintain, version etc. without any gains. Are there any plans of releasing it on e.g. Maven as the previous connector was?

**Comment by rajmera3** [comment]
Hi @bbs-csel,

Thanks for the question! We are actively working on this and hope to have the connector available on Maven very soon.

**Comment by rajmera3** [comment]
#19

**Comment by shivsood** [comment]
https://github.com/microsoft/sql-spark-connector/pull/29 is handling this.

**Comment by AlphaAnalyticsAUS** [comment]
Is there any update on this. When will this be available on Maven

**Comment by rajmera3** [comment]
The connector is available on Maven now under spark-mssql-connector! All future releases will be made here - https://search.maven.org/search?q=spark-mssql-connector
