### ISSUE TITLE
reliabilityLevel NO_DUPLICATES always produces `Cannot drop the table` error message

### ISSUE THREAD

**Issue by paulstaab** [microsoft/sql-spark-connector#180]
When using the `ReliableSingleInstanceStrategy` with v1.2.0, I consistently get the error message

```
22/03/25 10:52:53 ERROR ReliableSingleInstanceStrategy: cleanupStagingTables: Exception while dropping table [##local-1648205267894_schema.table_0] :Cannot drop the table '##local-1648205267894_schema.table_0', because it does not exist or you do not have permission.
22/03/25 10:52:53 ERROR ReliableSingleInstanceStrategy: cleanupStagingTables: Exception while dropping table [##local-1648205267894_schema.table_1] :Cannot drop the table '##local-1648205267894_schema.table_1', because it does not exist or you do not have permission.
[...]
```

This message is somewhat scary, because it implies that users might fill up the temp-storage of the db over time. However, the data is written correctly and no global temp tables remain.

Looking at the code, I assume that the error message comes from the [first execution of `cleanupStagingTables` ](https://github.com/microsoft/sql-spark-connector/blob/b26d95321600b469836b6204f455f7c5237d4382/src/main/scala/com/microsoft/sqlserver/jdbc/spark/connectors/ReliableSingleInstanceStrategy.scala#L54) before any data is written. Here, I would except that it is normal that the temp tables do not exist. Can we suppress the error message in this case?

**Comment by luxu1-ms** [comment]
@paulstaab CleanupStagingTables happens before and after staging table writing. Yes the error message you see is probably from dropping staging tables before data loading, and the staging tables have not been created yet, so that the error message you see is expected. The reason we have this message is because we need to make sure no staging table exists before we create them. It might be possible spark crashes half we when loading data and the staging tables still exists in the db.

**Comment by luxu1-ms** [comment]
Close the issue for now. Please reopen it if you have more questions.

**Comment by paulstaab** [comment]
@luxu1-ms Sorry, but I disagree here. Users should not get a scary error message for something that is perfectly normal and happens in almost all cases. You are totally correct that we need to make sure that the tmp tables are not there before writing to them, but I see no reason to alarm users with the error message - it should long be raised if the tables can not be deleted after writing in my eyes.

I am happy to contribute a PR to solve this issue. Do you want me to?

**Comment by luxu1-ms** [comment]
@paulstaab Yes it makes sense. I will review it. Thanks!
