### ISSUE TITLE
Azure SQL write not consuming all available DTU

### ISSUE THREAD

**Issue by darrenpricedcww** [microsoft/sql-spark-connector#184]
Is there anything I can do to make the connector utilise all available DTU in Azure SQL?
Seems to be something throttling the amount of DTU that is being used

I upped to Azure SQL tier from S3 to S6 but the timing didn't improve and the DTU consumed by the woirte process never goes over 22%

Databricks Cluster: 10.4 LTS
Driver: com.microsoft.azure:spark-mssql-connector_2.12:1.2.0

Spark config:
df.write \
  .format('com.microsoft.sqlserver.jdbc.spark') \
  .mode('append') \
  .option('url', databaseUrl) \
  .option('dbtable', tableName) \
  .option('accessToken', accessToken) \
  .option('mssqlIsolationLevel', 'READ_UNCOMMITTED') \
  .option('reliabilityLevel', 'BEST_EFFORT') \
  .option('tableLock', 'true') \
  .option('BatchSize', 1048576) \
  .option('schemaCheckEnabled', 'false') \
  .save()

**Comment by darrenpricedcww** [comment]
![Untitled](https://user-images.githubusercontent.com/69020756/166503713-3f260de9-e9e2-4c1e-8c77-cc9669dacfa2.jpg)

**Comment by luxu1-ms** [comment]
@darrenpricedcww 
1. Do you have any secondary SQL? It might hold the resources. 
2. The disk latency also plays an important role.
3. Can you check the partition size? The BatchSize should be greater than each partition size.

**Comment by luxu1-ms** [comment]
Close inactive issues. Please reopen it if not resolved.
