### ISSUE TITLE
Comparison to "com.databricks.spark.sqldw"

### ISSUE THREAD

**Issue by malthe** [microsoft/sql-spark-connector#188]
Databricks provides its own [Spark driver to Azure Synapse](https://docs.databricks.com/data/data-sources/azure/synapse-analytics.html).

How does it compare to the Apache Spark Connector for SQL Server and Azure SQL (this project) – ?

How do both of these projects compare to [Azure Synapse Dedicated SQL Pool Connector for Apache Spark](https://docs.microsoft.com/en-us/azure/synapse-analytics/spark/synapse-spark-sql-pool-import-export) (which is available only when using Azure Synapse Workspace and presumably the equivalent of the Databricks driver) – ?

**Comment by afogarty85** [comment]
Also curious about this issue.

**Comment by shanyu** [comment]
1) Databricks’s "Spark driver to Azure Synapse": can read/write data from/to Azure Synapse, via a temporary Azure Storage folder.

2) Synapse Spark "Dedicated SQL Pool Connector for Apache Spark": can be used by Synapse Spark to read/write data from/to Synapse Dedicated SQL Pool, via a temporary Azure Storage folder (for external table, directly read from storage).

I think the differences are that our connector is only for on-prem SQL Server or Azure SQL DB, data is sent via JDBC and making use of SQL Server’s bulk load API, where those Synapse connectors use temporary staging storage folder to send data.

**Comment by malthe** [comment]
@shanyu but there is already a JDBC driver: https://github.com/Microsoft/mssql-jdbc.

**Comment by shanyu** [comment]
That mssql-jdbc is used by a single client to talk to a SQL Server instance. The sql-spark-connector actually uses the jdbc driver to send partitioned Spark DataFrame to SQL Server instance in parallel, with bulk insert option.

**Comment by afogarty85** [comment]
Is there a plan to support Azure Synapse? Or would the performance be effectively similar as compared to: Synapse Spark "Dedicated SQL Pool Connector for Apache Spark"

**Comment by luxu1-ms** [comment]
Currently the connector can be used for Synapse.

**Comment by afogarty85** [comment]
> Currently the connector can be used for Synapse.

Any ideas on how to get past this?

```IllegalArgumentException: Invalid value `Read uncommitted` for parameter `isolationLevel`. This can be `NONE`, `READ_UNCOMMITTED`, `READ_COMMITTED`, `REPEATABLE_READ` or `SERIALIZABLE`.```

I have tried each value with Azure Synapse only to receive the same error.

**Comment by afogarty85** [comment]
Has anyone been able to write data to Synapse SQL with `com.microsoft.sqlserver.jdbc.spark`? I can read data using the connector but I cannot write data; the spark jobs hang.

**Comment by jjrugu** [comment]
@afogarty85 have you tried changing the `mssqlIsolitationLevel`? [Here's](https://learn.microsoft.com/en-us/sql/connect/spark/connector?view=sql-server-ver16#specify-the-isolation-level) the official documentation about how to change the isolation level. The default for dedicated SQL pools is READ_UNCOMMITED ([docs](https://learn.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-develop-transactions#transaction-isolation-levels)).

**Comment by afogarty85** [comment]
@jjrugu Thank you I got it to work! Any tips to speed up data ingestion with Synapse by chance? As compared with the databricks connector, `com.databricks.spark.sqldw`, inserting a test table of 3 million rows takes nearly a minute longer. I am using these parameters and playing mostly with the batch size.

```
    .option("reliabilityLevel", "BEST_EFFORT") \
    .option("tableLock", "true") \
    .option('batchsize', 1000000) \
    .option('truncate', 'true') \
    .option("mssqlIsolationLevel", "READ_UNCOMMITTED").save()
```

I am curious about this parameter, `dataPoolDataSource` but cannot find any documentation on it.

**Comment by malthe** [comment]
@afogarty85 the JDBC connector is row-based while the Databricks connector is column-based (it uses Parquet format internally which is similar or equal to the Synapse on-disk format).

**Comment by luxu1-ms** [comment]
> @jjrugu Thank you I got it to work! Any tips to speed up data ingestion with Synapse by chance? As compared with the databricks connector, `com.databricks.spark.sqldw`, inserting a test table of 3 million rows takes nearly a minute longer. I am using these parameters and playing mostly with the batch size.
> 
> ```
>     .option("reliabilityLevel", "BEST_EFFORT") \
>     .option("tableLock", "true") \
>     .option('batchsize', 1000000) \
>     .option('truncate', 'true') \
>     .option("mssqlIsolationLevel", "READ_UNCOMMITTED").save()
> ```
> 
> I am curious about this parameter, `dataPoolDataSource` but cannot find any documentation on it.

For spark mssql connector, dataPoolDataSource option used when read / write to Big Data Cluster Data Pool external table. please see example [here](https://github.com/microsoft/sql-spark-connector/blob/v1.2.0/samples/PySpark%20Connector%20with%20Big%20Data%20Clusters.ipynb)
