### ISSUE TITLE
Can you comit code to Synapse analytics?

### ISSUE THREAD

**Issue by katerinagreif** [microsoft/sql-spark-connector#189]
Hi, I would like to know if you can connect to Synapse Analytics Workspace with this connector and commit a piece of code generated to the server there. Similar to what you can do with pyodbc for other databases?

**Comment by shivsood** [comment]
not sure if i understand this correctly. Can u please elaborate on what do you mean by commit code? The connector can be used in spark 2.x and spark 3.x. Its used to write data to sql from spark.

**Comment by luxu1-ms** [comment]
Close inactive issue
