### ISSUE TITLE
Id column results in number of column mismatch 

### ISSUE THREAD

**Issue by kaykumar** [microsoft/sql-spark-connector#193]
This seems not working still with connector version com.microsoft.azure:spark-mssql-connector_2.12:1.2.0.

the workaround for now is to add id column with a 0 as value and MSSQL will auto increment it.

_Originally posted by @kaykumar in https://github.com/microsoft/sql-spark-connector/issues/14#issuecomment-1182503249_

**Comment by luxu1-ms** [comment]
The workaround is generate a auto increased column and connector will auto fill the column.

**Comment by luxu1-ms** [comment]
close inactive issue
