### ISSUE TITLE
jar-with-dependencies is not generated

### ISSUE THREAD

**Issue by kkhambadkone** [microsoft/sql-spark-connector#205]
The program complains that com.microsoft.sqlserver.jdbc.SQLServerDriver class is not found.   If this class is excluded then it says no suitable driver.   How can we generate the jar-with-dependencies jar file.  The default pom.xml only generates the basic jar without this class.

**Comment by moredatapls** [comment]
it is very unclear what exactly you're trying to do. are you building it from the sources yourself? could you please share step by step what you were doing?

**Comment by kkhambadkone** [comment]
I am building from sources.  I downloaded both the repos sql-spark-connector and tsolytic-sql-spark-connector
both dont build with dependencies jar.   I had to add the dependencies plugin and then it did build the jar with the Driver.

    On Sunday, October 30, 2022 at 03:57:23 PM PDT, Helge Brügner ***@***.***> wrote:  
 
 This message is eligible for Automatic Cleanup! ***@***.***) Add cleanup rule | More info
 


it is very unclear what exactly you're trying to do. are you building it from the sources yourself? could you please share step by step what you were doing?

**Comment by luxu1-ms** [comment]
If you use mvn build, the jar file does not contain its dependancies. You will have to add the dependency jars in the classpath. Please reopen if you have more questions.
