### ISSUE TITLE
How-To build the jar using SBT

### ISSUE THREAD

**Issue by fsanchez145** [microsoft/sql-spark-connector#211]
I apologize for the question.
However, I don't know how to build the jar using SBT.
Your help and/or guidance is greatly appreciated.

**Comment by luxu1-ms** [comment]
We have maven build for this project. Please use 'mvn package' to build the jar.

**Comment by fsanchez145** [comment]
Hi, thanks for the quick response.
I have installed a few things on my desktop.
1. Java 1.8 jdk
2. Python 3.11
3. sbt
4. Visual Studio Code, which I installed the Maven for Java
However, getting some errors.
[VSCodeMavenError.txt](https://github.com/microsoft/sql-spark-connector/files/10710755/VSCodeMavenError.txt)
do I need to run mvn package from sbt?
Do you have actual step-by-steps?

**Comment by fsanchez145** [comment]
I have installed Apache Maven 3.9.0 and failed to compile.
I have attached the error file.
[mavenPackageCreationError-2nd.txt](https://github.com/microsoft/sql-spark-connector/files/10711286/mavenPackageCreationError-2nd.txt)

**Comment by luxu1-ms** [comment]
We have also published the jars in Maven Central https://search.maven.org/search?q=spark-mssql-connector

**Comment by fsanchez145** [comment]
That is great to know...

**Comment by fsanchez145** [comment]
Thanks for your help Luxu1-ms.  I want to know if I have the wrong Maven and SBT installed, which causing the compile to fail.
