### ISSUE TITLE
Connection closed on cluster with 3.3.0

### ISSUE THREAD

**Issue by TMTck** [microsoft/sql-spark-connector#214]
Hi There,

Thank you very much for update this with 3.3.0. I have been waiting for this since last year. However, I do have some issues using it. 

The configuration that I'm using is similar to what documented. However, when I ingest 1 rows, it's working, anything else doesn't. In my test, i'm trying 200 rows, connection closed. 

Can you advise what have I been doing wrong please? 

Cluster: 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/98612912/220464978-cd0de693-36a0-4223-9137-54d6812a1877.png">
Error:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/98612912/220464749-3e3bcab1-43c3-4941-be2d-f7084f6b6b7d.png">
Library installation
<img width="424" alt="image" src="https://user-images.githubusercontent.com/98612912/220464878-2954c84a-c51b-450f-abda-0d7de5e7b07b.png">

**Comment by TMTck** [comment]
Correction, none of the use case is working. It is not ingested, it is just not showing connection closed error.

**Comment by luxu1-ms** [comment]
Could you please provide the repro?

**Comment by luxu1-ms** [comment]
Close inactive issue
