### ISSUE TITLE
Spark connector version for Spark 3.2.x

### ISSUE THREAD

**Issue by hiumingw** [microsoft/sql-spark-connector#221]
Hi, we are currently on spark 3.2.x and using Spark connector 1.2.0.  On project  version matrix , I see 1.2.0 is recommended for Spark 3.1.x and 1.3.0 is recommended for Spark 3.3.x.  Please share your thoughts on which version should be used for 3.2.x

thanks

**Comment by luxu1-ms** [comment]
Please use 1.2.0.
