### ISSUE TITLE
Support for Spark 3.4.0

### ISSUE THREAD

**Issue by psolomin** [microsoft/sql-spark-connector#227]
I've tried this connector with Spark 3.4.0 on Java 17 and it seems working for basic write and read operations. Is there a full test set anywhere which must run before Spark 3.4.0 support is added in the README?

P.S.: I needed to exclude Scala dependency:

```
    implementation("com.microsoft.azure:spark-mssql-connector_2.12:1.3.0-BETA") {
        exclude group: 'org.scala-lang'
    }
```

Otherwise it was conflicting with Spark's scala 2.12.17

**Comment by hlngo** [comment]
@psolomin Can you elaborate on how to exclude Scala dependency? What file should I add your snippet to? I am new & trying to set up pyspark 3.4.0 on my local machine.

**Comment by psolomin** [comment]
Hello @hlngo 

> What file should I add your snippet to?

It's in my `build.gradle` - I use Gradle to create a set of jars for Spark to use. Here's a part of my `build.gradle` file:

```
configurations {
    userLibs.extendsFrom implementation
}

dependencies {
    // this are used for spark.driver.extraClassPath and spark.executor.extraClassPath
    userLibs("com.microsoft.azure:spark-mssql-connector_2.12:1.3.0-BETA") {
        exclude group: 'org.scala-lang'
    }
}

task copyUserDeps(type: Copy) {
    from configurations.userLibs
    into "${userDepsLocation}"
}
```

When I run `./gradlew copyUserDeps` it fetches stuff under `dependencies` + all transitive dependencies and puts them into `userDepsLocation` which I configure.

Then, when I run my apps, I use:

```
spark-submit ... --conf spark.driver.extraClassPath="$userDepsLocation/*" --conf spark.executor.extraClassPath="$userDepsLocation/*"
```

Hope it helps.

**Comment by zhukovgreen** [comment]
Trying the same thing, but problems on writing:
```
java.lang.NoSuchMethodError: 'org.apache.spark.sql.types.StructType org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.getSchema(java.sql.ResultSet, org.apache.spark.sql.jdbc.JdbcDialect, boolean)'
```
Tried on jdk8 and 11

**Comment by psolomin** [comment]
Thanks for sharing the details @zhukovgreen !

I think, in all my use cases timestamps were passed to MS SQL as strings. If I bump into the same issue I will think of forking and patching this.

**Comment by psolomin** [comment]
@zhukovgreen just a follow-up:

I've tried inserting `timestamp` Spark types into `smalldatetime` column, and it worked fine. I will run further checks there anyway though.

**Note:** In my use-cases, I don't let Spark creating tables, they are created via plain SQL in a different tool, with indexes, etc. Spark only writes there.
