### ISSUE TITLE
Cannot write to table with computed column

### ISSUE THREAD

**Issue by chenfeiw** [microsoft/sql-spark-connector#25]
I have a table like this:
Create table Test
(
Id int,
Year nvarchar(4),
Month nvarch(2),
Date As (Year + '-' + Month)
)

Because Date is a computed column, my dataframe doesn't have this column, I get exception 'Spark Dataframe and SQL Server table have different numbers of columns'.

**Comment by shivsood** [comment]
does this work with default JDBC connector. 
Here's what needs to be done to support this.
1. Support option to not do a strict check
2. Utilize SqlBulkCopyColumnMapping during bluk copy to map specific columns.

**Comment by chenfeiw** [comment]
Yes, it works with default JDBC.

**Comment by shivsood** [comment]
Fix would be required to support a non-strict option. Also Utilize SqlBulkCopyColumnMapping during bulk copy to map specific columns.

**Comment by shivsood** [comment]
Looks same as #14

**Comment by pmooij** [comment]
> does this work with default JDBC connector?
> Here's what needs to be done to support this.
> 
> 1. Support option to not do a strict check
> 2. Utilize SqlBulkCopyColumnMapping during bluk copy to map specific columns.

indeed, these 2 features are needed to deal with Identity, Computed & Defaults constraints.
quite cumbersome to do the workarrounds now

**Comment by rajmera3** [comment]
Solved in #52
