### ISSUE TITLE
Should natively Handle AzureSQL Serverless - Sleep/Pause Mode and not fail

### ISSUE THREAD

**Issue by sandeep540** [microsoft/sql-spark-connector#27]
When connecting to AzureSQL Serverless which are configured to go to sleep/pause mode [Mostly in Dev/Stage], Spark should not fail, rather it should wait for 5-7 sec and retry 3 times before throwing exception

**Comment by shivsood** [comment]
Support for Azure SQL serverless. @rajmera3 @arvindshmicrosoft FYI

**Comment by mokabiru** [comment]
@sandeep540 could you please also paste the error message and the environment you are testing in - Spark standalone? Databricks?

**Comment by sandeep540** [comment]
Spark standalone

**Comment by B4PJS** [comment]
You can always set the connection timeout property to >30s in the jdbc url and in my experience this works

**Comment by shivsood** [comment]
Spark does re-try based on configuration, and connector retry depends on Spark driver/executor retrying. Closing as non-issue/resolved.
