### ISSUE TITLE
Require Support to Read/Write from ADLS2 (Azure Data Lake Storage V2) from spark connector with simple connection

### ISSUE THREAD

**Issue by sandeep540** [microsoft/sql-spark-connector#28]
Require Support to Read/Write from ADLS2 (Azure Data Lake Storage V2) from spark connector with simple connection and **not** have complex dependencies and jars

**Comment by shivsood** [comment]
@sandeep540 Can u please elaborate. I am not clear on this ask. @rajmera3

**Comment by shivsood** [comment]
Closing as this appears an ask on bundling connector with the respective service. Not a spark connector issue.
