### ISSUE TITLE
Support for .NET for Apache Spark

### ISSUE THREAD

**Issue by rrekapalli** [microsoft/sql-spark-connector#34]
Does this connector support "[.NET for Apache Spark](https://github.com/dotnet/spark)"?  Could you please provide an example to use this connector to read/write data to/from SQL Server stand alone instance (Not Azure/cloud based SQL Server)

**Comment by shivsood** [comment]
Connector use the DataSource interface. All supported spark bindings ( R, Scala, Python ...) should work. 

"".NET for Apache Spark"? is new spark binding. If this is supported in your spark version, then the connector should work. Never tested this on .Net, so please let us know if you have any findings.


>>provide an example to use this connector to read/write data to/from SQL Server stand alone instance (Not Azure/cloud based SQL Server)
Please refer to the Samples folder. All these sample work for any SQL server ( OnCloud or OnPrem). Choose the right authentication method ( basic auth, keytab based or AAD for Azure SQL).
