### ISSUE TITLE
Support Questions (relation to DataBricks)

### ISSUE THREAD

**Issue by dbeavon** [microsoft/sql-spark-connector#37]
The readme says this connector is only supported in conjunction with "SQL Server Big Data Clusters".

How is the support insofar as Azure Databricks is concerned?    Can I open a ticket with Azure Databricks about this connector?

It seems like this SQL connector would be a central component for solutions that use Databricks to load data into Azure SQL.  It would seem that Microsoft engineers should be focusing on this connector to ensure the success of both their Databricks and their Azure SQL customers.  Am I wrong?  Am I missing something?

There seems to be a wide diversity of products within the Microsoft "big data" platform, and I may be misunderstanding the importance of "Azure Databricks".  Perhaps it is prioritized beneath some other competing offerings (eg. Synapse, Big Data Clusters).  Is it likely that Databricks will never get the same support that is available for some of the competing products in Azure?

I am not very familiar with the "big data" platform at Microsoft, or the related opensource communities.  I still find it really confusing when certain critical components (like this connector) seem to lack the full support and sponsorship of Microsoft.  (Another similar one is ".Net for Spark").  

Azure Databricks 7.0 was released two months ago, and surely it was under development for many months prior.  It seems like Microsoft could have had a SQL connector that was ready for us to use by now.  Or perhaps it is the JDBC connector that is the only officially supported mechanism for interacting with Azure SQL?  Any clarification would be appreciated.

**Comment by rajmera3** [comment]
Hi,

There is no Microsoft support for the Apache Spark Connector for SQL Server and Azure SQL today. Users should field issues/questions/concerns on this repository and contributors will assist as possible.

**Comment by dbeavon** [comment]
OK.  That is pretty clear, but disappointing.

Does this github project also get used by the new azure synapse workspaces preview (https://docs.microsoft.com/en-us/azure/synapse-analytics/overview-what-is ) ?  Or maybe they have their own clone of this code?

I'm wondering if they will place a more critical dependency on this connector in the future, and offer some level of "official support".  It seems truly strange that we don't already have an officially-supported connector for SQL in Azure-DataBricks that is able to perform bulk inserts from a dataframe.

I do appreciate your effort on this connector, and I was able to get it up and running fairly easily on spark 3, with just a few tweaks to build.sbt.  I trust that I can't go too far wrong by using this version of the connector.  My only concern is related to the optics of not having any official Microsoft support.
