### ISSUE TITLE
Does it support bulk copy when reading? If not, why? Is there any limitation in azure sql sdk?

### ISSUE THREAD

**Issue by indianmifan** [microsoft/sql-spark-connector#41]
Does it support bulk copy when reading? If not, why? Is it because of any limitation in azure sql sdk?

**Comment by arvindshmicrosoft** [comment]
Not sure we understand your question correctly. Conceptually, the terms "bulk copy" or "bulk insert" are applied to the case where data is ingested *into* SQL. It would help if you can elaborate and explain your question / concerns.

**Comment by shivsood** [comment]
For read path is same as that of spark jdbc connector. bulk copy optimization is only supported for writes.
