### ISSUE TITLE
Cannot ingest data from spark into data pool running from external spark cluster

### ISSUE THREAD

**Issue by emacastelli** [microsoft/sql-spark-connector#44]
I'm trying to ingest data with a spark job from kafta into big data cluster's data pool, by running the spark job in an external spark cluster (external to the big data cluster). This is my configuration into the .py:

`datapool_table = 'SYSLOG_TEST_TABLE'
datasource_name = 'SqlDataPool'
url = 'jdbc:sqlserver://192.168.14.150:31433;database=sales;'
logs_df.write.format('com.microsoft.sqlserver.jdbc.spark').mode('append').option('url', url).option('dbtable', datapool_table).option('user', user).option('password', password).option('dataPoolDataSource',datasource_name).save()`

I'm getting this error:

`Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The TCP/IP connection to the host data-0-1.data-0-svc, port 1433 has failed. Error: "data-0-1.data-0-svc. Verify the connection properties. Make sure that an instance of SQL Server is running on the host and accepting TCP/IP connections at the port. Make sure that TCP connections to the port are not blocked by a firewall.".`

Is it possible to load into a data pool from an external spark cluster? Is there any configuration in the big data cluster that must be set up?

Thank you

**Comment by rajmera3** [comment]
@shanyu @shivsood This is a BDC error. Is there something they need to enable?

**Comment by uc-msft** [comment]
This is not supported scenario since the data pool instances are not exposed outside the kubernetes cluster. As a result, the service name resolution will fail. You will have to run the job on the cluster that contains the data pool & pull from the source instead.
