### ISSUE TITLE
Add support to execute SQL codes on Database

### ISSUE THREAD

**Issue by bellowman** [microsoft/sql-spark-connector#60]
the legacy spark connector had an option to execute custom SQL codes such as executing stored procedure to a target database, https://github.com/Azure/azure-sqldb-spark#pushdown-query-to-azure-sql-database-or-sql-server .

It will be also be nice if the home page or sample folder has more example of how to use the functions in https://github.com/microsoft/sql-spark-connector/blob/master/src/main/scala/com/microsoft/sqlserver/jdbc/spark/utils/BulkCopyUtils.scala

**Comment by rajmera3** [comment]
Please refer to #21.

> While the older Azure SQL DB Spark connector did include this functionality, since this new one is based on the Spark DataSource APIs, it is out of scope.
> 
> This functionality is provided by libraries like pyodbc.
