### ISSUE TITLE
NoClassDefFoundError while trying to read db table

### ISSUE THREAD

**Issue by akspande1989** [microsoft/sql-spark-connector#61]
```
server_name = "jdbc:sqlserver://mydbsample.database.windows.net"
database_name = "dbsample"
url = server_name + ";" + "database_name=" + database_name + ";"

table_name = "[SalesLT].[Product]"
username = "akshay"
password = "Password_1" # Please specify password here

try:
  jdbcDF = spark.read \
        .format("com.microsoft.sqlserver.jdbc.spark") \
        .option("url", url) \
        .option("dbtable", table_name) \
        .option("user", username) \
        .option("password", password).load()
except ValueError as error :
    print("Connector read failed", error)
```

I tried to test the Spark connector using the above in Databricks (installed by creating a jar file using sbt and uploading to cluster). 

Received the following error at line `.option("password", password).load()`

`java.lang.NoClassDefFoundError: org/apache/spark/internal/Logging$class`
[detailed_error.txt](https://github.com/microsoft/sql-spark-connector/files/5467363/detailed_error.txt)

Could you please help?

**Comment by akspande1989** [comment]
This is resolved now, was using a wrong cluster version. Using 6.6 now.

But there seems to be an issue with reading from camel case tables like SalesLT.Product. It reads fine from lowercase tables:

`com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name &#39;SalesLT.Product&#39;.`

**Comment by rajmera3** [comment]
@akspande1989 Your issue may be addressed here: https://github.com/microsoft/sql-spark-connector#migrating-from-legacy-azure-sql-connector-for-spark

**Comment by arvindshmicrosoft** [comment]
Hello @akspande1989 you are likely using a Databricks Runtime with Spark 3.x. That is not supported for this connector at this time, though there are efforts underway to implement it. For now, I suggest you use a Databricks Runtime with Spark 2.4.x to work around.
