### ISSUE TITLE
Support for DML Statements

### ISSUE THREAD

**Issue by rahulunlimited** [microsoft/sql-spark-connector#68]
Is there support for any DML available e.g. UPDATE, DELETE, MERGE on the datasets as I could not find them on the example.
If no, what are the suggested options.

**Comment by hmayer1980** [comment]
I would also look for support for any kind of SQL Statement to Execute, not necessarily DML, but for example also Exec procedure.  As this was possible with the prev version of the drivers ( with com.microsoft.azure:azure-sqldb-spark:1.0.2 I could just do sqlContext.sqlDBQuery and the Config could contain any String as queryCustom). Maybe we just miss examples for that.

**Comment by gbrueckl** [comment]
I am also really looking forward to this!
It would greatly increase the usability of the connector and allow us to do some proper ETL from/to Databricks/Spark

**Comment by SrinadhaYarram-SEGH** [comment]
Merge Functionality will be super helpful and avoid multiple code base in SQL and Databricks. Looking forward to Merge functionality either supporting Delta table or with Parquet files.

**Comment by rajmera3** [comment]
Hi all,

As mentioned in #21

While the older Azure SQL DB Spark connector did include this functionality to execute DML and DDL statements, since this connector is based on the Spark DataSource APIs, it is out of scope.

This functionality is provided by libraries like pyodbc.
