### ISSUE TITLE
Database schema

### ISSUE THREAD

**Issue by wboleksii** [microsoft/sql-spark-connector#70]
I don't see an option to specify database schema (if you need to use something other than "dbo"). How to write a table to non-default schema?

**Comment by ZMon3y** [comment]
I've had success just using the full <schema>.<tablename> as the string passed to option dbtable:

db_table = "Lic.foo"

 df.write \
   .format("com.microsoft.sqlserver.jdbc.spark") \
   .mode("overwrite") \
   .option("truncate",True) \
   .option("url",jdbc_url) \
   .option("dbtable", db_table) \
   .option("user", username) \
   .option("password", password) \
   .save()

This will write to the table Lic.foo
