### ISSUE TITLE
Error - com.microsoft.sqlserver.jdbc.SQLServerDriver does not allow create table as select

### ISSUE THREAD

**Issue by nevedya** [microsoft/sql-spark-connector#72]
Hello,

I get error connecting to Azure SQL Server database when using spark connector using DataBricks notebook. DataBricks cluster has the spark connector loaded. Any help appreciated.

Trying to extract data from parquet files in DataBricks and load into Azure SQL servere database.

Following the example mentioned in https://docs.microsoft.com/en-us/sql/connect/spark/connector?view=sql-server-ver15

I have used 2 different options to create SQL Server database

1. Azure Dedicated SQL Pool (formerly SQL DW)

2. Synapse workspace dedicated SQL pool

To extract data I use

df = spark.read.parquet("abfss://ctre@sns345.dfs.core.windows.net/Extract/*.parquet")

I have com.microsoft.azure:spark-mssql-connector:1.0.1 installed on databricks cluster and use the below code to load data into SQL Server database on Azure.

ERROR java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerDriver does not allow create table as select.

server_name = "jdbc:sqlserver://esqlserver.database.windows.net,1433"

database_name = "dedpool"

url = server_name + ";" + "databaseName=" + database_name + ";"

table_name = "dbo.spark_test1"

username = "ETL"

password = xxxx

try:

df.write \

.format("com.microsoft.sqlserver.jdbc.SQLServerDriver") \

.mode("append") \ .option("url", url) \

.option("dbtable", table_name) \

.option("user", username) \

.option("password", password) \

.save()

except ValueError as error : print("Connector write failed", error)

Thanks,

**Comment by B4PJS** [comment]
format is wrong

.format("com.microsoft.sqlserver.jdbc.spark")

**Comment by shivsood** [comment]
Closing as resolved. Thanks @B4PJS
