### ISSUE TITLE
Support for Spark 3.0 or above

### ISSUE THREAD

**Issue by maqshifengw** [microsoft/sql-spark-connector#74]
We are looking to use SQL bulk copy with Databricks runtime 7.3, which supports Spark 3.0 and above. Can you please let us know what the plan is to make the Spark SQL connector compatible with at least Spark 3.0?
<img width="289" alt="Spark version" src="https://user-images.githubusercontent.com/77037916/103727707-c5f53b00-4f90-11eb-98cf-ebe3a0b397dd.png">

**Comment by ZMon3y** [comment]
See https://github.com/microsoft/sql-spark-connector/issues/15
