### ISSUE TITLE
Login Failed for SQL User

### ISSUE THREAD

**Issue by rajkve** [microsoft/sql-spark-connector#8]
![image](https://user-images.githubusercontent.com/67467517/85856517-c89ef880-b7d5-11ea-80d7-5e6cd9604f71.png)

com.microsoft.sqlserver.jdbc.SQLServerException: Login failed for user 'AZURE_DBRICKS_USER'. ClientConnectionId:99b4b16e-d74b-44e3-aed5-b408589e16ea

I have no idea what is wrong with this, using sql spark [connector ](https://github.com/microsoft/sql-spark-connector/blob/master/samples/.DS_Store)it works pretty fine

Note: connection info removed from the picture on purpose

**Comment by shivsood** [comment]
Looks like incorrect credentails issue. Please check with defalt JDBC connector if you suspect this is not a login issue. Replace "com.microsoft.sqlserver.jdbc.spark" with "jdbc".

**Comment by rajkve** [comment]
> Looks like incorrect credentails issue. Please check with defalt JDBC connector if you suspect this is not a login issue. Replace "com.microsoft.sqlserver.jdbc.spark" with "jdbc".

**Comment by rajkve** [comment]
No - it isn't due to incorrect credentials - the same credential works fine in SSMS & also for https://github.com/microsoft/sql-spark-connector

**Comment by rajkve** [comment]
ok - issue is resolved with the below connection string 
```
// Create the JDBC URL without passing in the user and password parameters.
val jdbcUrl = s"jdbc:sqlserver://${jdbcHostname}:${jdbcPort};database=${jdbcDatabase}"
```
