### ISSUE TITLE
Update command

### ISSUE THREAD

**Issue by Rajendramca** [microsoft/sql-spark-connector#85]
How to execute update clause using this connector

**Comment by ZMon3y** [comment]
AFAIK that is out of scope for this connector.  That can be achieved with the regular JDBC connector.

**Comment by B4PJS** [comment]
Can be done like so using default JDBC:

# COMMAND ----------

# DBTITLE 1,Secrets
jdbcUsername = dbutils.secrets.get(scope = 'AzureKeyVault', key = 'sqladminusername')
jdbcPassword = dbutils.secrets.get(scope = 'AzureKeyVault', key = 'sqladminpassword')
server = dbutils.secrets.get(scope = 'AzureKeyVault', key = 'azuresqlserver')
database = dbutils.secrets.get(scope = 'AzureKeyVault', key = 'azuresqldatabase')

url = "jdbc:sqlserver://{SERVER_ADDR};databaseName={DATABASE_NAME};loginTimeout=65535;".format(SERVER_ADDR = server,DATABASE_NAME = database)

#for executing non-queries
driver_manager = spark._sc._gateway.jvm.java.sql.DriverManager
con = driver_manager.getConnection(url, jdbcUsername, jdbcPassword)



# COMMAND ----------

# DBTITLE 1,Drop Staging Table
drop = "DROP TABLE IF EXISTS Stage.dimExample"

stmt = con.createStatement()
stmt.executeUpdate(drop)
stmt.close()
