### ISSUE TITLE
How to use this connector on Spark Pool provided by Azure Synapse Analytics

### ISSUE THREAD

**Issue by piotrgwiazda** [microsoft/sql-spark-connector#93]
I am trying to use this connector to connect to Azure SQL Database instance from Azure Synapse Analytics Spark Pool.
It would be great o have documentation on:
- How to add the connector to Synapse Spark Pool
- How to connect to Azure SQL Database using Linked Service and Token Library

Currently trying do upload this jar to a Spark Pool in Synapse Analytics Spark Pools causes session error on start.

**Comment by piotrgwiazda** [comment]
This was temporarily solved by building a new version of the connector that supports 8.4.1.jre8. When is the release planned?
See: https://stackoverflow.com/a/67124073/221951

**Comment by shivsood** [comment]
@piotrgwiazda spark sql connector usage is in samples. For bundling connector with the specific service and service specific samples e.g. " Azure SQL Database using Linked Service and Token Library" please work with the respective product team.
