### ISSUE TITLE
Can we use bulkCopyToSqlDB for PySpark using this connector?

### ISSUE THREAD

**Issue by archanabwk** [microsoft/sql-spark-connector#95]
I want to use SQL bulk insert option with this MSSQL Connector, but I couldn't find any way or example for the same.
Is there any PySpark example available for SQL Bulk Insert option?

**Comment by arvindshmicrosoft** [comment]
Please refer to the [useful notebooks from Davide Mauri, showing how to best use bulk insert with partitioning from Spark - in this case, Azure Databricks, and sweeping through the variety of options for table design](https://github.com/Azure-Samples/azure-sql-db-databricks/tree/main/notebooks). The method you are referring to is probably from an older connector, which is no longer supported. This connector just uses the regular df.write() method. Please see the samples I linked to.

**Comment by VaiAhuja** [comment]
Hi @arvindshmicrosoft, we were using bulkCopyToSqlDB and it was working fine. We upgraded to spark 3.2.1, post upgrade bulkCopyToSqlDB is not working. We tried using df.write but it is taking lot of time to copy data with large number of records.
Is there any other optimized way of copy large set of data?

**Comment by vlasvlasvlas** [comment]
its there a more optimized way of copying large set of data than df.write?

**Comment by arvindshmicrosoft** [comment]
The df.write.format("com.microsoft.sqlserver.jdbc.spark") method enabled by using this connector, does use the SQL Bulk Copy APIs, which are currently the fastest way to ingest large amounts of data into Azure SQL DB / SQL Server.

**Comment by vlasvlasvlas** [comment]
great, i'll check that. thanks!
