### ISSUE TITLE
Error - java.lang.NoClassDefFoundError: com/microsoft/sqlserver/jdbc/ISQLServerBulkData

### ISSUE THREAD

**Issue by S-Gayathri24** [microsoft/sql-spark-connector#98]
Hello,

I get error connecting to Azure SQL Server database when using sql spark connector using DataBricks notebook. 
Trying to extract data from parquet files in DataBricks and load into Azure SQL servere database.
Installed Mavan Coordinate com.microsoft.azure:spark-mssql-connector:1.0.1 on Spark 2.4.5 compatible connnector and Installed jar file which is created using SBT. Followed ( https://docs.microsoft.com/en-us/sql/connect/spark/connector?view=sql-server-ver15) document from Microsoft. 

try:
  df_merge.write \
    .format("com.microsoft.sqlserver.jdbc.spark") \
    .mode("overwrite") \
    .option("url", url) \
    .option("dbtable", table_name) \
    .option("user", username) \
    .option("password", password) \
    .save()
except ValueError as error :
    print("Connector write failed", error)

Error:  java.lang.NoClassDefFoundError: com/microsoft/sqlserver/jdbc/ISQLServerBulkData

Any help appreciated.

Thanks.

**Comment by luxu1-ms** [comment]
@S-Gayathri24 Cam you check your jdbc version? I guess the spark mssql connector you use built with jdbc 8.4.1, but the jdbc in your  environment is jdbc-7.*

**Comment by shivsood** [comment]
closing as old/answered. Please open if still an issue after using the right JDBC version.

**Comment by skypiece** [comment]
It is 100% wrong jdbc driver used.
Need to remove old jar from environment and replace it by mssql-jdbc-8.4.1.*.jar

**Comment by marcin2x4** [comment]
> It is 100% wrong jdbc driver used. Need to remove old jar from environment and replace it by mssql-jdbc-8.4.1.*.jar

In my case, I had two jars in `/opt/spark/jars`:

```
mssql-jdbc-7.0.0.jre8.jar
mssql-jdbc-8.4.1.jre8.jar
```

Removing version `7` fixed below error:

```
An error occurred while calling o142.save.
: java.lang.SecurityException: class "com.microsoft.sqlserver.jdbc.ISQLServerBulkData"'s signer information does not match signer information of other classes in the same package
    at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)
    at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
    at java.security.SecureClas...
```
