### ISSUE TITLE
How do we keep the metadata information of an array column when inserting into a database?

### ISSUE THREAD

**Issue by fabienarnaud** [microsoft/sql-spark-connector#99]
I have a quite complex XML with several nested columns and arrays to load into my Azure SQL database.
The connector works great and stores arrays in my nvarchar columns in the form "WrappedArray([])" for example:

WrappedArray([verificatie,[individual specifier,[Onderwerpen Projectplanning aan Monte Carlo analyse - opstartfase,[null,ME_01044]],[null,Planningsmanagement]]])

The problem is that only values are stored, not the metadata. XML element and attribute names are lost which then makes it complex to parse.
Is there any way to keep the metadata along when writing these array and nested columns?

**Comment by shivsood** [comment]
@fabienarnaud Not clear. Please clarify what's your dataframe , what was written to SQL ad what were you expecting. Note : connector does not translate any columns/value in the dataframe. If u have Spark String column type ( which has XML) in your dataframe, this when written to SQL will be mapped to nvarchar.

**Comment by shivsood** [comment]
Closing the issue as no response. Please open with details/repro if still an issue.

**Comment by fabienarnaud** [comment]
Hi Shivsood,

Sorry for the late answer but since I left this aside for a while, I forgot to scan the new comments.
What I meant is that I have a data frame with a group of columns like this:

![image](https://user-images.githubusercontent.com/59871287/129384422-e6901944-eed1-4d06-abfe-61d2bb97fc46.png)

In Databricks, it displays like this:

<img width="293" alt="array column" src="https://user-images.githubusercontent.com/59871287/129384502-8fc96aba-8fd1-4a9c-bfd4-a8b81ce73a68.PNG">

The problem is when I write this dataframe to my Azure SQL DB, I only see this:

![image](https://user-images.githubusercontent.com/59871287/129384662-ba77c494-b213-44ec-9e27-38fcd2c685b7.png)

The column names that were visible in Databricks (11, 12, 13) are lost along the way, which makes it hard to further process the contents of this column array.

Is there any option somewhere that allows the metadata i.e. the column names to be captured together with the data upon writing to the DB?
